baseURL = "https://rltimeline.com"
languageCode = "en-us"
title = "Reinforcement Learning Playbook"
theme = "timeline"

[Params]
video = "DQN Breakout.mp4"
header = "RL Playbook"
timelineTitle = "How RL Evolved"

[markup.goldmark.renderer]
unsafe= true